### DISCUSSION TITLE
MWE for loading remote files

### DISCUSSION THREAD

**Discussion by sgbaird** [pyscript/pyscript#2244] [Q&A] [answered]
I'm converting https://honegumi.readthedocs.io/ to use PyScript to dynamically generate outputs as a function of input selections in a grid rather than generating all combinations in advance (for scalability reasons). However, I've been having trouble getting it to recognize and load files (either from a remote location or from within the same repository).

- https://github.com/sgbaird/honegumi/blob/dev/docs/honegumi_pyscript_helper.py
- https://github.com/sgbaird/honegumi/blob/dev/docs/honegumi.html
- https://github.com/sgbaird/honegumi/blob/dev/docs/constants.py

Here are examples of a few of the files I'd like to use -- https://github.com/sgbaird/honegumi/blob/dev/src/honegumi/core/_honegumi.py, https://github.com/sgbaird/honegumi/blob/dev/src/honegumi/ax/utils/constants.py) -- these are part of a package. The idea was to use links to the GitHub direct download files from the `main` branch.

Some other things I've tried: https://github.com/sgbaird/honegumi/tree/dev/docs/pyscript-examples

Given the project context, does this seem like a reasonable approach to begin with?

I'll try to loop back with a better summary of what I've already tried and the resources for it, but I've been stuck on it for a while.

Related:
- https://github.com/pyscript/pyscript/discussions/1290

Would https://github.com/mudream4869/pyscript-local-package#files be suitable in combination with a GitHub Actions step to commit the wheel based on each commit to main? It seems like this would bloat the repo size a fair bit.

**Comment by sgbaird** [comment]
Perhaps this is what I need (reversing order):

https://discord.com/channels/972017612454232116/972020206538997822/1301811276862722068

https://pyscript.com/@laffra/ltk-on-micropython/latest?files=main.py,pyscript.toml

**Reply by sgbaird** [reply]
The problem seems to be the use of a redirect URL, which is the URL you get from right-clicking on "raw" (see below for [constants.py](https://github.com/sgbaird/honegumi/blob/main/src/honegumi/ax/utils/constants.py)).

![image](https://github.com/user-attachments/assets/7027ceac-a62d-40b7-9cff-eb8edbd41c0f)

Note that the download icon doesn't point to a URL, it's some kind of javascript action

![image](https://github.com/user-attachments/assets/fe939161-5a6d-4547-8e45-3d53f3f1177a)

So, to quickly get the link, either modify the following:

```
https://raw.githubusercontent.com/<USERNAME>/<REPO>/refs/heads/main/<PATH>
```

or click on "raw", let it redirect you, and then copy the URL from the browser bar (e.g., `https://raw.githubusercontent.com/sgbaird/honegumi/refs/heads/main/src/honegumi/ax/utils/constants.py`)

## 

Example `pyscript.toml` below:
```toml
name = "LTK on MicroPython Copy"

[files]
# # Correct, same format as above (LTK examples)
# "https://raw.githubusercontent.com/sgbaird/honegumi/main/src/honegumi/ax/utils/constants.py" = "constants.py"

# Correct download URL (i.e., copied from browser bar after clicking "raw" and letting it redirect)
"https://raw.githubusercontent.com/sgbaird/honegumi/refs/heads/main/src/honegumi/ax/utils/constants.py" = "constants.py"

# # Default "copy link address" from "raw" button (e.g., https://github.com/sgbaird/honegumi/blob/main/src/honegumi/ax/utils/constants.py), makes "world" button disappear. Maybe other issues. Likely because this is a redirect URL
# "https://github.com/sgbaird/honegumi/raw/refs/heads/main/src/honegumi/ax/utils/constants.py" = "constants.py"
```

##
EDIT:

Additionally, I needed to use `type="mpy"` instead of `type="py"` to avoid getting the `ModuleNotFoundError: No module named 'constants'` error. I'm not sure why.

```html
<script type="mpy" src="main.py" config="pyscript.toml"></script>
```

Related: https://docs.pyscript.net/2024.10.2/user-guide/first-steps/


##
EDIT: I'm also having issues with versions of pyscript.

`https://pyscript.net/releases/2024.10.2/core.js` seems OK. But https://docs.pyscript.net/2024.10.2/beginning-pyscript/ also has a script for loading a pyscript css file and leads to the "arrr" translate button not displaying any output.
