### DISCUSSION TITLE
Support --no-deps/deps=False install for packages

### DISCUSSION THREAD

**Discussion by jtroe** [pyscript/pyscript#2341] [Proposals]
As a user, I would like to be able to specify a package I would like, and manually manage dependencies.

e.g. in pyscript.toml
```toml
packages = ["arcgis --no-deps"]
```
(or whatever syntax makes the most sense, if it becomes an object or something)

from python, I can use micropip to install the package (it is failing to import after this, but I'm confident there is a way to make it work)
```python
import pyodide_js
await pyodide_js.loadPackage('micropip')
import micropip
await micropip.install("arcgis >=2.4.1", deps=False)
import arcgis # fails currently, may need to do the install on js before loading the script
```

Similar issue: https://github.com/pyscript/pyscript/discussions/2298

**Comment by WebReflection** [comment]
I am personally not too keen to find a solution that works for only 1 out of many fields `micropip.install` accepts:
https://micropip.pyodide.org/en/v0.7.1/project/api.html#micropip.install

I actually wonder if having something like this would be a nice addition to our packages featutres/abilities:

```toml
[package.arcgis]
version=">=2.4.1" # optional
keep_going=False # optional
deps=True # optional
credentials=None # optional
pre=False # optional
index_urls=None # optional
verbose=None # optional
```

A list of `package.xxxx` could be available and power-users would have full control over these details ... heck this could also be parsed before regular packages, when present, to ensure that if further packages have dependencies these are already available ... would that make sense or be useful?
