### ISSUE TITLE
py-splashscreen + py-terminal visual issues

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1362]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In a page with 100% height and content that covers 100% of such space, when pyscript loads pyodide the payout can't stretch full-height because both elements are appended on the page, so that I had to use:

```css
/* avoid splashscreen breaking layout */
py-splashscreen {
  position: absolute !important;
}
py-terminal {
  position: absolute !important;
}
```

On top of that, we make the `.py-overlay` position fixed but that container is basically useless because the `py-splashscreen` can, and should, already be styled as such + the py-terminal should not occupy any space on the page until everything is loaded, also because once everything is loaded both elements stop taking space on the page and everything looks fine again.

### Additional Context

There is some general cleanup needed in our styles but most importantly we style extra nodes that feel unnecessary for the container they work in ... but if we want a component to be full screen size and fixed, we better make that container as such and not its internals, otherwise the container might mess up other full size layouts while loading.
