### ISSUE TITLE
[FEATURE] workflow: add auto tag release to workflow

### ISSUE THREAD

**Issue by Kalkulus1** [pyscript/pyscript#333]
The current workflow doesn't have an auto-tagging release. We could add that to generate an auto tag for patch, minor and major releases if needed.

```yaml
     - name: Automatic Tagging of Releases
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: rymndhng/release-on-push-action@v0.23.1
        id: tag-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          release_body: "This is the first official release for pyscript"
```

Then you can get the tag if you need to use it:
```yaml
IMAGE_TAG: ${{ steps.tag-release.outputs.tag_name }}
```
